---
variables:
    GIT_SUBMODULE_STRATEGY: recursive
build:
  image: pacxx/ubuntu
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_CXX1Y=ON -DCMAKE_CXX_FLAGS_RELEASE="-O3" -DCMAKE_INSTALL_PREFIX=$PWD/../local -DRV_ENABLE_SLEEF=ON -DRV_INCLUDE_DIR=$PWD/tools/rv/include
    - make -j${NUM_CORES:-1} install
  artifacts:
    paths:
    - local/
    expire_in: 30 days
